const SORT_BY_NAME = "SORT_BY_NAME";
const SORT_BY_SIZE = "SORT_BY_SIZE";
const SORT_BY_CREATION_DATE = "SORT_BY_CREATION_DATE";

const messageDisappearTime = 5000;

export { SORT_BY_NAME, SORT_BY_SIZE, SORT_BY_CREATION_DATE };