const GET_FOLDERS = "GET_FOLDERS";

const CHANGE_SORT_CRITERIA = "CHANGE_SORT_CRITERIA";

const SHOW_MESSAGE = "SHOW_MESSAGE";
const HIDE_MESSAGE = "HIDE_MESSAGE";

export { GET_FOLDERS, CHANGE_SORT_CRITERIA, SHOW_MESSAGE, HIDE_MESSAGE };