const GET_FOLDERS = "GET_FOLDERS";
const GET_FOLDERS_SUCCESS = "GET_FOLDERS_SUCCESS"
const GET_FOLDERS_ERROR = "GET_FOLDERS_ERROR";

const CHANGE_SORT_CRITERIA = "CHANGE_SORT_CRITERIA";

const SHOW_MESSAGE = "SHOW_MESSAGE";
const HIDE_MESSAGE = "HIDE_MESSAGE";

export { GET_FOLDERS, GET_FOLDERS_SUCCESS, GET_FOLDERS_ERROR, CHANGE_SORT_CRITERIA, SHOW_MESSAGE, HIDE_MESSAGE };